FROM node:18 AS ui-build
WORKDIR /root/
COPY frontend ./frontend/
RUN cd frontend && npm install && npm run build

FROM node:18 AS server-build
WORKDIR /root/
COPY --from=ui-build /root/frontend/build /frontend/build 
COPY backend ./backend/
RUN cd backend && npm install

EXPOSE 3080

CMD ["node", "./backend/server.js"]